### ISSUE TITLE
Looking Good

### ISSUE THREAD

**Issue by kumavis** [kumavis/aurigami#4]
![image](https://cloud.githubusercontent.com/assets/1474978/4112211/b2ee8966-321f-11e4-9e87-340f7ef64162.png)

pull latest, migrate, clear your posts db (optional)
run npm start in `app` and `sound_server`

and navigate to `/posts/`

record some posts, record some responses.
obviously the interaction is very poor but the basics are there.

we should chart out a road map for overhauling the interaction.

**Comment by flyswatter** [comment]
Oh man, how did this ever take me so long to try?  This is inches from "mvp"!!

When I click the "add post" button, I currently get a full error, with a pretty hairy stack trace (I'll do my best).

![screen shot 2015-05-25 at 8 44 10 pm](https://cloud.githubusercontent.com/assets/542863/7804951/1367c16a-031f-11e5-9235-bcc980919916.png)

**Comment by flyswatter** [comment]
The view you got working (in the screenshot above) is the `posts/show` endpoint, which allows replies to a single post to be viewed & added.

I've noticed the normal posts/add endpoint doesn't even have record buttons, which makes me think you built this on top of an already partly-populated database, so you didn't need to create new posts through it.

That said, this still doesn't solve why this error is happening, it should at least be a dumb form.

**Comment by kumavis** [comment]
nice work! glad you picked this up we did get pretty close

**Comment by kumavis** [comment]
My guess is that you are right, we need a non-empty db

**Comment by kumavis** [comment]
but you're the geddy guy ; ) so you might need to pursue that stack

**Comment by kumavis** [comment]
going to close this b/c the original issue is just a ui status update

**Comment by kumavis** [comment]
@flyswatter I'm also inclined to think that Geddy might be overkill

**Comment by danfinlay** [comment]
I never used Geddy views!  I used it as an API server.  This is only a problem with the view-building.  I'm inclined to whip up a quick minimal Ember app to serve the UI.  Overkill over overkill?

I also did my first Rails at work this week.. Maybe I'll do all the basic sql type rest api stuff in that, seems like a simple solution for that kind of thing, since you already have the streaming media handling in its own node server.

**Comment by kumavis** [comment]
hah -- I mean it seems like the whole server would just be

``` js
var app = express()
var db = levelup('./mydb')

app.put('/login', function(req, res) {
  loginUser(req, function(err){
    if (err) return res.status(500).send(err)
    res.status(200).send()
  })
})

app.put('/create', function(req, res) {
  checkAuth(req, function(err, userId){
    if (err) return res.status(500).send(err)
    var id = uuid()
    var data = extractPostData(req)
    db.put(id, data, function(err){
      if (err) return res.status(500).send(err)
      res.status(200).send()
    })
  })
})

app.get('/:node_id', function(req, res) {
  var id = req.params.node_id
  db.get(id, function(err, data){
    if (err) return res.status(500).send(err)
    res.status(200).send(data)
  })
})

app.listen(PORT)
```

ok so im not handling upvotes or actual auth,
but this just seems more appropriately lightweight for our needs

**Comment by danfinlay** [comment]
And maybe the most short-sightedly, you're not touching on users/auth, emails for password recovery, that whole nasty world that can be replaced by a popular rails gem.

**Comment by kumavis** [comment]
@flyswatter true

**Comment by danfinlay** [comment]
And actually, Geddy provides this out of the box, too, and it's just not _fully_ configured yet.

**Comment by kumavis** [comment]
I'll keep my sanity by invoking the power of the black box

**Comment by danfinlay** [comment]
Basically..  It's sad, but it's the boring stuff anyways.  If we can shove all the boring stuff into the easy-place, then we can focus on the cool stuff (implementation, streaming, play order, platforms, etc)

**Comment by kumavis** [comment]
yeah all about experimenting with that interaction!

oh dang i forgot that auth is necessary for writing to the streaming audio db...
hmm, unless you proxy through the authed api -- seems heavy

**Comment by kumavis** [comment]
so i dont think we should not record authorship in the audio db
the question is should the audio db allow an unknown user to record data

allow:
would be able to record any audio up to the time limit, and orphaned records would get GC'd regularly

disallow:
the auth api could create a record (and give you the id) to record against -- where the audio db requires you to have an id for a record in an open state to record against, which after recording goes to a closed state

**Comment by kumavis** [comment]
I think calculating orphanhood (we may still need to GC old items depending on disk limitations) would be more complex than having the api create an 'open record'. Also some anti-spam protections. I like it.
